name: "Test service using Kind"

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    types:
      - 'closed'
    branches:
      - 'main'
      
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          pip install ruff pytest pytest-cov 
    
      - uses: actions/checkout@v3
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
      - name: Testing
        run: |
          kubectl wait nodes --for condition=Ready --all
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
      
      - name: Deploy Application
        run: |
          kubectl create deployment rock-paper-scissors-app --image=${{ env.REGISTRY }}/${{ github.repository }}:main
          kubectl wait pods --for condition=Ready --timeout=90s --all
          #          kubectl get pods -o wide --all-namespaces --watch
          kubectl expose deployment/rock-paper-scissors-app --type=NodePort --port 5000
      
      - name: Test Deployment on Server
        run: |
          kubectl describe services/rock-paper-scissors-app
          kubectl port-forward service/rock-paper-scissors-app 5000:5000 > /dev/null &
          ENDPOINT=http://localhost:5000 pytest tests/integration
      
      - name: Cleanup
        if: always()
        run: |
          kind delete cluster --name test-cd-rock-paper-scissors-app
          
      - name: Running pytest Coverage
        run: |
          PYTHONPATH="${PYTHONPATH}:./src" python -m pytest -v tests/integration --cov
      
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
      
          
