name: "Test service using Kind"

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    types:
      - 'closed'
    branches:
      - 'main'
      
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  kind:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo "Docker Image Build and Push successful."
      
      - uses: actions/checkout@v3
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
      - name: Testing
        run: |
          kubectl wait nodes --for condition=Ready --all
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
      
      - name: Deploy Application
        run: |
          kubectl create deployment rock-paper-scissors-app --image=${{ env.REGISTRY }}/${{ github.repository }}:main
          kubectl wait pods --for condition=Ready --timeout=90s --all
          kubectl expose deployment/rock-paper-scissors-app --type=NodePort --port 5000
      
      - name: Test Deployment
        run: |
          kubectl describe svc rock-paper-scissors-app
          kubectl port-forward service/rock-paper-scissors-app 5000:6000 > /dev/null &
          ENDPOINT=http://localhost:5000 pytest tests/integration
      
      - name: Cleanup
        if: always()
        run: |
          kind delete cluster --name test-cd-rock-paper-scissors-app
          
